#!/usr/bin/env python3
r"""The positive cross-moment demo (JHEP, Z+jet section).

The sixteen windowed joint moments <w1 w2 T_k(u(ptj1)) T_n(u(ptj2))> of the
jet pair, as pulls against fixed order (NLO Zj, 40 seeds, seed-scatter
errors).  The prior sits 3.7-80 sigma off (median 21).  Constraining the
two MARGINAL towers transports the joint to ~1 sigma (median 1.07) -- the
same correlation transport that predicts phi* -- but a residual up to
3.3 sigma survives because the QCD dijet correlation does not factorize.
Imposing the 16 cross moments closes it to <=0.5 sigma (median 0.07),
at 5pp of effN (57.4 -> 52.3%).

Numbers from zj_cross_demo.py + zj_cross_err.py (checked in alongside this
script), regenerated 2026-08-17 against zj_moments2 (clipped-map binary,
mll = BW map, 40 seeds).
"""
import os
import sys

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from pubstyle import use_pub_style, C
use_pub_style(base=18)

#              FO        sigma   prior     marginals  +16 mixed
DATA = {(1, 1): (+0.0275, 0.0004, +0.0361, +0.0280, +0.0275),
        (1, 2): (-0.0065, 0.0041, +0.0648, -0.0092, -0.0064),
        (1, 3): (-0.0670, 0.0011, -0.0903, -0.0688, -0.0672),
        (1, 4): (+0.0250, 0.0019, -0.0058, +0.0280, +0.0250),
        (2, 1): (+0.1763, 0.0026, +0.2360, +0.1765, +0.1762),
        (2, 2): (+0.7908, 0.0004, +0.7770, +0.7906, +0.7910),
        (2, 3): (-0.4609, 0.0067, -0.6107, -0.4623, -0.4609),
        (2, 4): (-0.4885, 0.0026, -0.4001, -0.4891, -0.4885),
        (3, 1): (-0.0695, 0.0014, -0.0983, -0.0704, -0.0697),
        (3, 2): (-0.0027, 0.0099, -0.1826, +0.0062, -0.0028),
        (3, 3): (+0.1748, 0.0037, +0.2465, +0.1758, +0.1744),
        (3, 4): (-0.0620, 0.0049, +0.0211, -0.0714, -0.0620),
        (4, 1): (-0.1487, 0.0013, -0.1803, -0.1508, -0.1489),
        (4, 2): (-0.6097, 0.0026, -0.6194, -0.6046, -0.6093),
        (4, 3): (+0.3887, 0.0036, +0.4711, +0.3938, +0.3883),
        (4, 4): (+0.3987, 0.0007, +0.3425, +0.3964, +0.3988)}


def main():
    global DATA
    effA, effB = 57.4, 52.3
    res = os.path.join(HERE, "zj_cross_results.npz")
    if os.path.exists(res):
        # regenerated by zj_cross_demo.py (+ sigma_FO from the seed scatter)
        R = np.load(res)
        DATA = {tuple(int(v) for v in mn): (float(fo), float(er), float(pr), float(ma), float(mi))
                for mn, fo, er, pr, ma, mi in zip(R["mn"], R["fo"], R["err"], R["prior"], R["marg"], R["mixed"])}
        effA, effB = 100 * float(R["effN_marg"]), 100 * float(R["effN_mixed"])
        print(f"using zj_cross_results.npz ({len(DATA)} joint moments, {int(R['n_events']):,} events)")
    keys = sorted(DATA)
    x = np.arange(len(keys))
    pull = lambda i: np.array([abs(DATA[k][i] - DATA[k][0]) / DATA[k][1] for k in keys])
    fig, a = plt.subplots(figsize=(8.6, 5.8))
    a.axhspan(0.0, 1.0, color="0.88", alpha=0.6, zorder=0)
    a.plot(x, pull(2), "s", color=C["prior"], ms=9, label=r"PS+LO prior")
    a.plot(x, pull(3), "o", color=C["mcatnlo"], ms=9,
           label=rf"marginal towers only ($N_\mathrm{{eff}}={effA:.1f}\%$)")
    a.plot(x, np.maximum(pull(4), 2e-2), "o", color=C["maxent"], ms=9,
           label=rf"$+16$ cross moments ($N_\mathrm{{eff}}={effB:.1f}\%$)")
    a.set_yscale("log")
    a.set_ylim(1.5e-2, 80)
    a.set_xticks(x)
    a.set_xticklabels([rf"$({m},{n})$" for m, n in keys], fontsize=11)
    a.set_xlabel(r"joint moment $\langle T_k(p_T^{j_1})\,T_n(p_T^{j_2})\rangle$,"
                 r"\ \ index $(k,n)$")
    a.set_ylabel(r"distance from fixed order $\ |\mu-\mu_{\rm FO}|/\sigma_{\rm FO}$")
    a.legend(loc="lower center", bbox_to_anchor=(0.5, 1.01), ncol=3, fontsize=12,
             frameon=False, handletextpad=0.4, columnspacing=1.2)
    a.text(0.985, 0.055, r"$|\mathrm{pull}|\le1$",
           transform=a.transAxes, ha="right", va="bottom", fontsize=11,
           color="0.35")
    out = os.path.join(HERE, "fig_zj_cross.pdf")
    fig.savefig(out); fig.savefig(out.replace(".pdf", ".png"))
    plt.close(fig)
    p = {i: pull(i) for i in (2, 3, 4)}
    print(f"pulls: prior {p[2].min():.1f}-{p[2].max():.1f} (median {np.median(p[2]):.1f});  marginals max {p[3].max():.2f} "
          f"(median {np.median(p[3]):.2f});  +mixed max {p[4].max():.2f} (median {np.median(p[4]):.2f})")
    print("wrote", out)


if __name__ == "__main__":
    main()
